# Generated by Django 5.1.1 on 2024-10-07 14:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("trading", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="portfolio",
            name="money_invested",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name="portfolio",
            name="profit_loss",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
    ]
